django/labellabor/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from two_factor.urls import urlpatterns as tf_urls
from labelbase.api import LabelAPIView, LabelbaseAPIView
from rest_framework.documentation import include_docs_urls
from django.contrib.auth.decorators import login_required

from userprofile.views import (ProfileView,
                               ProfileAvatarUpdateView,
                               ProfileCurrencyUpdateView,
                               MempoolUpdateView,
                               ProfileFeeUpdateView,
                               ElectrumInfoUpdateView)
from userprofile.views import APIKeyView
from userprofile.views import has_seen_welcome_popup



from hashtags.views import HashtagListView, HashtagUpdateView, LabelbaseProxyView


from .views import (
    UTXOsHealthView,
    LabelbaseHealthDatatableView,
    LabelbaseView,
    LabelbaseViewActionView,
    LabelbaseMergeView,
    LabelbaseDeleteView,
    LabelDeleteView,
    TermsView,
    HomeView,
    RegistrationCompleteView,
    LabelUpdateView,
    PrivacyView,
    RegistrationView,
    LabelbaseFormView,
    LabelbaseUpdateView,
    DonationView,
    AboutView,
    EncryptionView,
    InteroperationalView,
    CloudView,
    ExportLabelsView,
    # StatsAndKPIView,
    TreeMapsView,
    FixAndMergeLabelsView,
    LabelbaseDatatableView,
    #LabelbasePortfolioView,
    OutputStatUpdateRedirectView,
    BitcoinAddressDatatableView,
    CurrencySyncView,
    CurrencySyncActionView,
    FillMissingDataView,
    FillMissingDataActionView,
    FillOutputFieldsActionView
)


from importer.views import upload_labels
from django.contrib.auth import views as auth_views


urlpatterns = [
    path(
        "api/v0/labelbase/",
        LabelbaseAPIView.as_view()
    ),
    path(
        "api/v0/labelbase/<int:id>/",
        LabelbaseAPIView.as_view()
    ),
    path(
        "api/v0/labelbase/<int:labelbase_id>/label/",
        LabelAPIView.as_view()
    ),
    path(
        "api/v0/labelbase/<int:labelbase_id>/label/<int:id>/",
        LabelAPIView.as_view()
    ),
    path(
        "api-reference/",
        include_docs_urls(title="Labelbase API")
    ),
    path(
        "account/apikey/",
        login_required(APIKeyView.as_view()),
        name="apikey"
    ),
    path(
        "account/userprofile-avatar/",
        login_required(ProfileAvatarUpdateView.as_view()),
        name="userprofile_avatar",
    ),
    path(
        "account/userprofile-electrum/",
        login_required(ElectrumInfoUpdateView.as_view()),
        name="userprofile_electrum",
    ),
    path(
        "account/userprofile-mempool/",
        login_required(MempoolUpdateView.as_view()),
        name="userprofile_mempool",
    ),
    path(
        "account/userprofile-mempool-fees/",
        login_required(ProfileFeeUpdateView.as_view()),
        name="userprofile_fees",
    ),
    path(
        "account/userprofile-currency/",
        login_required(ProfileCurrencyUpdateView.as_view()),
        name="userprofile_currency",
    ),
    path(
        "account/userprofile/",
        login_required(ProfileView.as_view()),
        name="userprofile",
    ),
    path(
        "labelbase/<int:labelbase_id>/health/",
        login_required(UTXOsHealthView.as_view()),
        name="labelbase_health"
    ),
    path(
        "labelbase/<int:labelbase_id>/health/data/",
        login_required(LabelbaseHealthDatatableView.as_view()),
        name="labelbase_health_label_data"),
    path(
        "labelbase/<pk>/delete/",
        login_required(LabelbaseDeleteView.as_view()),
        name="del_labelbase"
    ),
    path(
        "labelbase/<int:labelbase_id>/",
        login_required(LabelbaseView.as_view()),
        name="labelbase"
    ),
    path(
        "labelbase/<int:labelbase_id>/hashtags/",
        login_required(HashtagListView.as_view()),
        name="labelbase_hashtags"
    ),
    path(
        "labelbase/<int:labelbase_id>/hashtags/proxy/",
        login_required(LabelbaseProxyView.as_view()),
        name="labelbase_hashtags_proxy"
    ),
    path(
        "labelbase/hashtag/<int:pk>/edit/",
        login_required(HashtagUpdateView.as_view()),
        name="hashtag_edit"
    ),
    path(
        "labelbase/<int:labelbase_id>/data/",
        login_required(LabelbaseDatatableView.as_view()),
        name="labelbase_label_data"),
    path(
        "labelbase/<int:labelbase_id>/actions/<str:action>/",
        login_required(LabelbaseViewActionView.as_view()),
        name="labelbase_actions"),
    path(
        "labelbase/<int:labelbase_id>/merge/",
        login_required(LabelbaseMergeView.as_view()),
        name="labelbase_merge"
    ),
    path(
        'labelbase/<int:labelbase_id>/currency-sync/',
        CurrencySyncView.as_view(),
        name='currency_sync'
    ),
    path(
        'labelbase/<int:labelbase_id>/currency-sync/action/',
        CurrencySyncActionView.as_view(),
        name='currency_sync_action'
    ),
    path(
        'labelbase/<int:labelbase_id>/fill-missing-data/',
        FillMissingDataView.as_view(),
        name='fill_missing_data'
    ),
    path('label/<int:label_id>/fill-output-fields/',
        FillOutputFieldsActionView.as_view(),
        name='fill_output_fields_action'),
    path(
        'labelbase/<int:labelbase_id>/fill-missing-data/action/',
        FillMissingDataActionView.as_view(),
        name='fill_missing_data_action'
    ),

    #path(
    #    "labelbase/<int:labelbase_id>/portfolio/",
    #    login_required(LabelbasePortfolioView.as_view()),
    #    name="labelbase_portfolio"
    #),
    path(
        "labelbase/<int:labelbase_id>/edit/",
        login_required(LabelbaseUpdateView.as_view()),
        name="edit_labelbase"
    ),
    path(
        "labelbase/import/",
        upload_labels,
        name="import_labels"
    ),
    path(
        "labelbase/<int:labelbase_id>/dyanmic-export/",
        login_required(ExportLabelsView.as_view()),
        name="labelbase_dynamic_export"
    ),
    path(
        "labelbase/<int:labelbase_id>/fix-and-manage/",
        login_required(FixAndMergeLabelsView.as_view()),
        name="labelbase_fix_and_manage"
    ),
    # path(
    #    "labelbase/<int:labelbase_id>/stats-and-kpi/",
    #    login_required(StatsAndKPIView.as_view()),
    #    name="labelbase_stats_and_kpi"
    # ),
    path(
        "labelbase/<int:pk>/tree-maps/",
        login_required(TreeMapsView.as_view()),
        name="labelbase_tree_maps"
    ),
    path(
        "labelbase/<int:pk>/tree-maps/<str:action>/",
        login_required(TreeMapsView.as_view()),
        name="labelbase_tree_maps"
    ),
    path(
        "labelbase/",
        login_required(LabelbaseFormView.as_view()),
        name="labelbase_new"
    ),
    path(
        "label/<int:pk>/edit/",
        login_required(LabelUpdateView.as_view()),
        name="edit_label"
    ),
    path(
        "label/<int:pk>/edit/<str:action>/",
        login_required(LabelUpdateView.as_view()),
        name="edit_label_with_action"
    ),
    path(
        "label/<int:pk>/delete/",
        login_required(LabelDeleteView.as_view()),
        name="del_label"
    ),
    path(
        "account/logout/",
        LogoutView.as_view(),
        name="logout"
    ),
    path(
        "account/register/",
        RegistrationView.as_view(),
        name="registration"
    ),
    path(
        "account/register/done/",
        RegistrationCompleteView.as_view(),
        name="registration_complete"
    ),
    path(
        "account/change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="change_password.html",
            success_url="/"
        ),
        name="change_password"
    ),
    path(
        "privacy-policy",
        PrivacyView.as_view(),
        name="privacy_policy"
    ),
    path(
        "terms",
        TermsView.as_view(),
        name="terms"
    ),
    path(
        "donate",
        DonationView.as_view(),
        name="donate"
    ),
    path(
        "about",
        AboutView.as_view(),
        name="about"
    ),
    path(
        "encryption",
        EncryptionView.as_view(),
        name="encryption"
    ),
    path(
        "interoperational",
        InteroperationalView.as_view(),
        name="interoperational"
    ),
    path(
        "cloud",
        CloudView.as_view(),
        name="cloud"
    ),
    path(
        "outputstat/<int:output_stats_id>/update/<int:label_id>/",
        login_required(OutputStatUpdateRedirectView.as_view()),
        name='outputstat_update_redirect'
    ),

    path(
        "label-derived-addresses/<int:label_id>/",
        login_required(BitcoinAddressDatatableView.as_view()),
        name='label_derived_addresses'
    ),

    path(
        "",
        HomeView.as_view(),
        name="home"
    ),
    path(
        "",
        include(tf_urls)
    ),
    path(
        "knowledge-base/",
        include('knowledge_base.urls')
    ),
    path(
        "",
        include("user_sessions.urls", "user_sessions")
    ),
    path(
        "attachments/",
        include('attachments.urls', namespace='attachments')
    ),
    path(
        "messages/",
        include("messages_extends.urls", "messages_extends")
    ),
    path(
        "has_seen_welcome_popup/",
        has_seen_welcome_popup,
        name='has_seen_welcome_popup'
    ),

]

urlpatterns.append(path("admin/", admin.site.urls))

django/labelbase/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .models import Label, Labelbase


class LabelbaseForm(forms.ModelForm):
    """ """
    class Meta:
        model = Labelbase
        fields = ["name", "fingerprint", "about",  "network"]
        # We will re-introdiuce "operation_mode" in the future


class LabelForm(forms.ModelForm):
    """ """
    class Meta:
        model = Label
        fields = ["labelbase", "type", "ref", "label", "origin", "spendable"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        self.labelbase_id = kwargs.pop("labelbase_id")
        super(LabelForm, self).__init__(*args, **kwargs)
        user_labelbases = Labelbase.objects.filter(
            user_id=self.request.user.id, id=self.labelbase_id
        )
        self.fields["labelbase"] = forms.ModelChoiceField(
            queryset=user_labelbases,
            required=True,
            widget=forms.HiddenInput(),
        )
        if user_labelbases.count() == 1:
            self.fields["labelbase"].initial = user_labelbases[0]

        # Add the "bip329-attr" class to the labels
        for field_name in self.fields:
            self.fields[field_name].label = mark_safe(
                f'<label class="bip329-attr">{self.fields[field_name].label}</label>')


class ExportLabelsForm(forms.Form):
    """ """
    tx_checkbox = forms.BooleanField(required=False, initial=True, label="tx")
    addr_checkbox = forms.BooleanField(required=False, initial=True, label="addr")
    pubkey_checkbox = forms.BooleanField(required=False, initial=True, label="pubkey")
    input_checkbox = forms.BooleanField(required=False, initial=True, label="input")
    output_checkbox = forms.BooleanField(required=False, initial=True, label="output")
    xpub_checkbox = forms.BooleanField(required=False, initial=True, label="xpub")
    encrypt_checkbox = forms.BooleanField(required=False, label="encrypt")
    passphrase = forms.CharField(widget=forms.PasswordInput, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['passphrase'].disabled = True

        # Add the "bip329-attr" class to the labels of checkboxes
        for field_name in ['tx_checkbox', 'addr_checkbox', 'pubkey_checkbox',
                           'input_checkbox', 'output_checkbox', 'xpub_checkbox']:
            self.fields[field_name].label = mark_safe(
                f'<label class="bip329-attr">{self.fields[field_name].label}</label>')

django/templates/_modal_connect_api_key.html
<div class="modal" tabindex="-1" id="connectApiKeyLabelbaseModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">API Connect</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          API Key: <strong><tt>{{ api_token }}</tt></strong>
        <br>
          Labelbase ID: <strong><tt>{{labelbase.id }}</tt></strong>
        <br>
          Base Endpoint: <strong><tt>https://labelbase.space/api/v0/</tt></strong><br>
          <small>NOTE: Replace "https://labelbase.space" with your own host. </small>
        </p>
        <center>
          <div style="padding:1.5em;" id="qrcode"></div>

          <div class="alert alert-warning" role="alert">
            API keys work like passwords. Keep them secret!<br>
            Whoever knows the key can access your labelbases.<br>
          </div>
        </center>
        <p>
          Our API reference can be found here: <br>
          <a href="https://labelbase.space/api-reference/">https://labelbase.space/api-reference/</a>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

django/templates/_modal_delete_labelbase.html
<div class="modal" tabindex="-1" id="deleteLabelbaseModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete labelbase and labels?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="alert alert-warning" role="alert">
         <strong>Warning:</strong>
         <br>
         <br>
         This action will permanently delete the labelbase and its labels and cannot be undone.
         <br><br>
         Are you sure you want to proceed?
        </div>
      </div>
      <form method="post" action="{% url 'del_labelbase' labelbase.pk %}">{% csrf_token %}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCEL</button>
        <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">DELETE</button>
      </div>
      </form>
    </div>
  </div>
</div>

django/templates/_modal_exportLabelbaseModal.html
{% load i18n %}
{% load labelbase_tags %}
{% load sekizai_tags %}
{% load bootstrap %}

{% if labelbase %}
<div class="modal" tabindex="-1" id="exportLabelbaseModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form id="export-label-form" action="{% url 'labelbase_dynamic_export' labelbase.id %}" method="post">
      {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title">Export BIP-329 Labels</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="export-label-modal-body">
          {% labelbaseform_export as export_form %}
          {{ export_form|bootstrap  }}
          <div id="export_enc_warning" class="alert alert-light" role="alert" style="margin-top:1.2rem;">
              <small>Labels are encrypted using our <a href="https://github.com/Labelbase/python-bip329">Python library for BIP-329</a>. <br>
                Always keep your passphrase secret and secure! </small>

          </div>
        </div>
        <div id="successMessage" class="alert alert-success d-none" role="alert" style="margin-top:1.2rem;">
            <strong>Success!</strong> Your export has been completed.
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="exportButton">Export</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% else %}
<!-- modal exportLabelbaseModal not loaded -->
{% endif %}


{% addtoblock "js" %}



    $("#export-label-form").submit(function(e) {
        // Remove the buttons and hide form fields
        $('#exportButton').prop('disabled', true);
        $('#export-label-modal-body').hide();

        // Display the success message
        $('#successMessage').removeClass('d-none');
    });

  // Enable/disable passphrase input based on the "Encrypt" checkbox
  const encryptCheckbox = $("#id_encrypt_checkbox");
  const passphraseInput = $("#id_passphrase");
  const exportButton = $("#exportButton");

  const formGroup = encryptCheckbox.closest(".form-group");
  const obj_hr = $("<hr>");
  const obj_br2 = $("<br>");

  formGroup.before(obj_hr); // Add <hr> before the parent form-group of the encryptCheckbox
  const passphraseLabel = $('label[for="id_passphrase"].control-label');
  passphraseLabel.before(obj_br2);

  // Create an array of all the checkboxes that should enable the Export button
  const checkboxesToMonitor = [
    $("#id_tx_checkbox"),
    $("#id_addr_checkbox"),
    $("#id_pubkey_checkbox"),
    $("#id_input_checkbox"),
    $("#id_output_checkbox"),
    $("#id_xpub_checkbox"),
  ];

  // Add change event handlers for all checkboxes
  checkboxesToMonitor.forEach(function(checkbox) {
    checkbox.change(toggleExportButton);
  });

  encryptCheckbox.change(function() {
    togglePassphraseInput();
    toggleExportButton();
  });

  passphraseInput.on("input", toggleExportButton);

  // Function to toggle the passphrase input state
  function togglePassphraseInput() {
    const isEncryptChecked = encryptCheckbox.prop("checked");
    passphraseInput.prop("disabled", !isEncryptChecked);
    if (!isEncryptChecked) {
      passphraseInput.val(""); // Empty passphrase input if encryption is not checked
    }
  }

  // Function to toggle the Export button state
  function toggleExportButton() {
    const isEncryptChecked = encryptCheckbox.prop("checked");
    var passphraseValue = "";
    if (passphraseInput.length) {
        passphraseValue = passphraseInput.val().trim();
    } else {
        console.log('passphraseInput element not found.');
    }

    const anyCheckboxChecked = checkboxesToMonitor.some(function(checkbox) {
      return checkbox.prop("checked");
    });

    // Disable the export button if encryption is checked and the passphrase is empty,
    // or if nothing is checked
    exportButton.prop("disabled", (isEncryptChecked && passphraseValue === "") || !anyCheckboxChecked);

    if (isEncryptChecked) {
      // If encryption is checked, add 'alert-warning' and remove 'alert-light'
      $('#export_enc_warning').addClass('alert-warning').removeClass('alert-light');
    } else {
      // If encryption is unchecked, add 'alert-light' and remove 'alert-warning'
      $('#export_enc_warning').addClass('alert-light').removeClass('alert-warning');
    }
  }

  $(document).ready(function() {

    // Initialize the button and input states
    togglePassphraseInput();
    toggleExportButton();
  });


{% endaddtoblock %}

django/templates/cloud.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}Interoperability{% endblock %}
{% block nav_home %}active{% endblock %}

{% block content %}
  <div class="p-3 pb-md-4 mx-auto text-center">
    <h1 style="padding-top: 1.6em; padding-bottom: 0.9em; text-transform: uppercase;font-weight:800;">L<span style="height:1.1em; width:1em" data-feather="tag" class="align-text-bottom"></span>belbase</h1>
    <h2 class="display-6 fw-normal" style="padding-bottom: 0.9em;">All your labels in one place.</h2>
  </div>



  <main class="lb-header mx-auto text-center">
    <!--
    "Use your labels here, use your labels there – Dave doesn't care."

    "Use this wallet today, use that wallet tomorrow – Dave doesn't care."
    -->
    <!-- Centered "Getting Started" CTA Block -->
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="mb-8">
                  <img src="/static/Cloud.png"
                class="card-img-top"
                alt="..."
                style="padding: 0.25em;">
                <div class="card-body">
                    <p style="font-weight: 700;">Cloud</p>

                    <p><i>"Use your labels here, use your labels there – Dave doesn't care."</i></p>
                    <p>
                      Be like Dave with Labelbase, your ultimate cloud-based platform for managing, merging, and synchronizing wallet labels across all your devices and wallet applications.

Labelbase seamlessly synchronizes your labels across various wallets and systems, ensuring you have consistent and organized data wherever you go. Simplify your financial management and stay in sync with Labelbase.
                    </p>


                    <p>
                       <br><br>
                      <a href="{{ reg_url }}" type="button" class="w-100 btn btn-lg btn-primary">Get started</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    </main>

{% endblock %}

django/templates/encryption.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}Encryption{% endblock %}
{% block nav_home %}active{% endblock %}

{% block content %}

  <div class="p-3 pb-md-4 mx-auto text-center">
    <h1 style="padding-top: 1.6em; padding-bottom: 0.9em; text-transform: uppercase;font-weight:800;">L<span style="height:1.1em; width:1em" data-feather="tag" class="align-text-bottom"></span>belbase</h1>
    <h2 class="display-6 fw-normal" style="padding-bottom: 0.9em;">All your labels in one place.</h2>
  </div>



  <main class="lb-header mx-auto text-center">

    <!-- Centered "Getting Started" CTA Block -->
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="mb-4 rounded-3">
              <img src="/static/Encryption.png" class="card-img-top" style="padding: 0.25em;">
                <div class="card-body">
                    <p style="font-weight: 700;">Your labels are encrypted.<br>&nbsp;</p>

                    <p>Your labels are encrypted using industrial-standard cryptography, ensuring a robust layer of protection for your data.</p>
                    <p>
                      <a href="{{ reg_url }}" type="button" class="w-100 btn btn-lg btn-primary">Get started</a>
                    </p>
                </div>
            </div>
        </div>
    </div>





    </main>

{% endblock %}

django/templates/labelbase_dt_ref.html
{% if mempool_url %}<a href="{{ mempool_url }}">{% endif %}
<tt>
  <span style="display:none;">{{ row.ref }}</span>
  <span class="connector-float-left d-block d-md-none">{{ row.ref|slice:"0:8" }}… {{  row.ref|slice:"-"|slice:"-8:" }}</span>
  <span class="connector-float-left d-none d-md-block d-lg-none">{{ row.ref|slice:"0:4" }}… {{  row.ref|slice:"-"|slice:"-4:" }}</span>
  <span class="connector-float-left d-none d-lg-block">{{ row.ref|slice:"0:10" }}… {{  row.ref|slice:"-"|slice:"-10:" }}</span>
</tt>
{% if mempool_url %}</a>{% endif %}

django/templates/labelbase_new.html
{% extends "_base.html" %}
{% load i18n %}
{% load bootstrap %}
{% block content %}
<div style="padding-top: 1em;">
<h2>New Labelbase</h2>
<form method="post" >
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="OK">
</form>
{% endblock %}

django/templates/labelbase_tree_maps.html
{% extends "_base.html" %}
{% load i18n %}
{% load sekizai_tags %}
{% load labelbase_tags %}
{% load importer_tags %}
{% load bootstrap %}

{% block content %}

{#% include "_labelbase_header_info_menu.html" %#}

<ul class="nav nav-tabs" style="padding-top: 2rem; ">
  <li class="nav-item">
    <a class="nav-link {% if action == "unspent-outputs" %}active" aria-current="page" {% else %}"{% endif %} href="{% url "labelbase_tree_maps" pk=labelbase.id %}unspent-outputs/">Unspent Outputs</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if action == "unspent-spendable-outputs" %}active" aria-current="page" {% else %}"{% endif %} href="{% url "labelbase_tree_maps" pk=labelbase.id %}unspent-spendable-outputs/">Unspent Spendable Outputs</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link {% if action == 'fee-efficiency' %}active{% endif %}"
       href="{% url 'labelbase_tree_maps' labelbase.id 'fee-efficiency' %}">
        Fee Efficiency (VTER)
    </a>
  </li>
</ul>



<div style="padding-top: 0rem; ">
{% block treemap %}
{% endblock %}
</div>




<script>
{% addtoblock "js" %}
{% endaddtoblock %}
</script>


{% endblock %}

django/templates/profile_update_currency.html
{% extends "_base.html" %}
{% load i18n %}
{% load sekizai_tags %}
{% load bootstrap %}

{% block content %}
{% include "profile_header_menu.html" %}
<div style="padding-top: 2rem; ">
{% block profile_content %}{% endblock %}
</div>

<p class="fs-6 text-muted">
  Select your preferred currency for displaying fiat values.
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form|bootstrap }}
      <tr>
        <td>&nbsp;</td>
        <td></td>
      </tr>
      <tr>
        <td colspan="2" style="text-align: center;">
          <button class="btn btn-primary" type="submit">Update currency</button>
        </td>
      </tr>
    </table>
  </form>
</p>
{% endblock %}

django/templates/upload.html
{% extends "_base.html" %}
{% load i18n %}
{% load bootstrap %}
{% block content %}
<h2 style="padding-top: 1em;">Import labels</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" value="OK">
</form>
{% endblock %}